import toast from 'react-hot-toast';

/**
 * Generate PDF using browser's native print functionality
 * This method prints the exact HTML/CSS/JS content without conversion issues
 */
export async function generatePDF(element, filename = 'document.pdf') {
  try {
    toast.loading('Preparing PDF...');

    // Clone the element to avoid modifying the original
    const clonedElement = element.cloneNode(true);
    
    // Create a new window for printing
    const printWindow = window.open('', '_blank', 'width=800,height=600');
    
    if (!printWindow) {
      throw new Error('Please allow pop-ups to download PDF');
    }

    // Get all stylesheets from the current document
    const styles = Array.from(document.styleSheets)
      .map(styleSheet => {
        try {
          return Array.from(styleSheet.cssRules)
            .map(rule => rule.cssText)
            .join('\n');
        } catch (e) {
          // Handle CORS issues with external stylesheets
          console.warn('Could not access stylesheet:', styleSheet.href);
          return '';
        }
      })
      .join('\n');

    // Get inline styles
    const inlineStyles = Array.from(document.querySelectorAll('style'))
      .map(style => style.innerHTML)
      .join('\n');

    // Build the print document
    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="utf-8">
          <title>${filename}</title>
          <style>
            /* Reset and print styles */
            * {
              margin: 0;
              padding: 0;
              box-sizing: border-box;
            }
            
            body {
              font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
              line-height: 1.6;
              color: #000;
              background: #fff;
            }

            /* Print-specific styles */
            @media print {
              body {
                margin: 0;
                padding: 20px;
              }
              
              @page {
                size: A4;
                margin: 20mm;
              }
              
              /* Avoid page breaks inside elements */
              h1, h2, h3, h4, h5, h6 {
                page-break-after: avoid;
              }
              
              img {
                max-width: 100%;
                page-break-inside: avoid;
              }
              
              table {
                page-break-inside: avoid;
              }
              
              /* Hide elements that shouldn't be printed */
              button, .no-print {
                display: none !important;
              }
            }

            /* Imported styles */
            ${styles}
            ${inlineStyles}
          </style>
        </head>
        <body>
          ${clonedElement.innerHTML}
        </body>
      </html>
    `);

    printWindow.document.close();

    // Wait for content to load
    await new Promise(resolve => {
      printWindow.onload = resolve;
      // Fallback timeout
      setTimeout(resolve, 1000);
    });

    toast.dismiss();
    toast.success('Opening print dialog...');

    // Trigger print dialog
    printWindow.focus();
    printWindow.print();

    // Close the window after printing (user can cancel)
    setTimeout(() => {
      printWindow.close();
    }, 100);

    return true;
  } catch (error) {
    console.error('Error generating PDF:', error);
    toast.dismiss();
    toast.error(error.message || 'Failed to generate PDF');
    throw error;
  }
}

/**
 * Generate PDF blob using browser's native print to PDF
 * Note: This requires user interaction to save the PDF
 */
export async function generatePDFBlob(element) {
  try {
    // For blob generation, we'll use the same print method
    // The user will need to select "Save as PDF" in the print dialog
    await generatePDF(element, 'document.pdf');
    
    // Return a placeholder blob since we can't programmatically capture the PDF
    // The actual PDF is generated by the browser's print dialog
    return new Blob(['PDF generated via print dialog'], { type: 'application/pdf' });
  } catch (error) {
    console.error('Error generating PDF blob:', error);
    throw error;
  }
}

/**
 * Alternative: Download HTML as a standalone file
 * This preserves all styling and can be opened in any browser
 */
export function downloadAsHTML(element, filename = 'document.html') {
  try {
    toast.loading('Preparing download...');

    // Get all styles
    const styles = Array.from(document.styleSheets)
      .map(styleSheet => {
        try {
          return Array.from(styleSheet.cssRules)
            .map(rule => rule.cssText)
            .join('\n');
        } catch (e) {
          return '';
        }
      })
      .join('\n');

    const inlineStyles = Array.from(document.querySelectorAll('style'))
      .map(style => style.innerHTML)
      .join('\n');

    // Create complete HTML document
    const htmlContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="utf-8">
          <title>${filename}</title>
          <style>
            ${styles}
            ${inlineStyles}
          </style>
        </head>
        <body>
          ${element.innerHTML}
        </body>
      </html>
    `;

    // Create blob and download
    const blob = new Blob([htmlContent], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    toast.dismiss();
    toast.success('HTML file downloaded!');
  } catch (error) {
    console.error('Error downloading HTML:', error);
    toast.dismiss();
    toast.error('Failed to download HTML');
    throw error;
  }
}
