import mongoose from 'mongoose';

const ServiceItemSchema = new mongoose.Schema({
  name: {
    type: String,
    required: true,
  },
  description: String,
  quantity: {
    type: Number,
    required: true,
    min: 1,
    default: 1,
  },
  unitPrice: {
    type: Number,
    required: true,
    min: 0,
  },
  discount: {
    type: Number,
    default: 0,
    min: 0,
    max: 100,
  },
  total: {
    type: Number,
    required: true,
  },
}, { _id: true });

const QuotationSchema = new mongoose.Schema({
  quotationNumber: {
    type: String,
    unique: true,
    required: false, // Will be auto-generated by pre-save hook
  },
  client: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Client',
    required: false, // Optional for immediate clients
  },
  clientName: {
    type: String,
    required: true,
  },
  clientEmail: {
    type: String,
    required: true,
  },
  clientPhone: String,
  companyName: String,
  gstNumber: String,
  billingAddress: {
    street: String,
    city: String,
    state: String,
    pincode: String,
    country: String,
  },
  projectTitle: {
    type: String,
    required: true,
  },
  projectDescription: String,
  services: [ServiceItemSchema],
  addOns: [{
    id: String,
    name: String,
    price: {
      type: Number,
      default: 0,
    },
    selected: {
      type: Boolean,
      default: false,
    },
  }],
  subtotal: {
    type: Number,
    required: true,
    default: 0,
  },
  discount: {
    type: Number,
    default: 0,
    min: 0,
  },
  taxRate: {
    type: Number,
    default: 18, // GST 18%
  },
  taxAmount: {
    type: Number,
    default: 0,
  },
  totalAmount: {
    type: Number,
    required: true,
    default: 0,
  },
  currency: {
    type: String,
    default: 'INR',
  },
  validTill: {
    type: Date,
    required: true,
  },
  paymentTerms: {
    type: String,
    default: '50% advance, 50% on completion',
  },
  notes: String,
  termsAndConditions: {
    type: String,
    default: 'Includes 3 minor revisions free of cost. Additional revisions or major scope changes may incur extra charges.',
  },
  status: {
    type: String,
    enum: ['draft', 'sent', 'viewed', 'accepted', 'rejected', 'expired', 'paid'],
    default: 'draft',
  },
  sentAt: Date,
  viewedAt: Date,
  acceptedAt: Date,
  rejectedAt: Date,
  // Payment fields
  paymentMethod: {
    type: String,
    enum: ['online', 'upi', 'cash', 'bank_transfer'],
  },
  paymentStatus: {
    type: String,
    enum: ['pending', 'processing', 'completed', 'failed', 'refunded'],
    default: 'pending',
  },
  razorpayEnabled: {
    type: Boolean,
    default: false,
  },
  razorpayOrderId: String,
  razorpayPaymentId: String,
  razorpaySignature: String,
  paidAmount: {
    type: Number,
    default: 0,
  },
  paidAt: Date,
  paymentNotes: String,
  createdBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
  },
  version: {
    type: Number,
    default: 1,
  },
  parentQuotation: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Quotation',
  },
}, {
  timestamps: true,
});

// Auto-generate quotation number BEFORE validation
QuotationSchema.pre('validate', async function() {
  if (!this.quotationNumber) {
    try {
      const date = new Date();
      const year = date.getFullYear();
      const month = String(date.getMonth() + 1).padStart(2, '0');
      
      // Get the model reference properly
      const QuotationModel = this.constructor;
      
      // Find the last quotation of this month
      const lastQuotation = await QuotationModel
        .findOne({ quotationNumber: new RegExp(`^QT${year}${month}`) })
        .sort({ quotationNumber: -1 })
        .lean();
      
      let sequence = 1;
      if (lastQuotation && lastQuotation.quotationNumber) {
        const lastSequence = parseInt(lastQuotation.quotationNumber.slice(-4));
        if (!isNaN(lastSequence)) {
          sequence = lastSequence + 1;
        }
      }
      
      this.quotationNumber = `QT${year}${month}${String(sequence).padStart(4, '0')}`;
      console.log('Generated quotation number:', this.quotationNumber);
    } catch (error) {
      console.error('Error generating quotation number:', error);
      // Fallback to timestamp-based number if generation fails
      this.quotationNumber = `QT${Date.now()}`;
    }
  }
});

// Auto-generate quotation number (backup hook)
QuotationSchema.pre('save', async function() {
  if (!this.quotationNumber) {
    try {
      const date = new Date();
      const year = date.getFullYear();
      const month = String(date.getMonth() + 1).padStart(2, '0');
      
      // Get the model reference properly
      const QuotationModel = this.constructor;
      
      // Find the last quotation of this month
      const lastQuotation = await QuotationModel
        .findOne({ quotationNumber: new RegExp(`^QT${year}${month}`) })
        .sort({ quotationNumber: -1 })
        .lean();
      
      let sequence = 1;
      if (lastQuotation && lastQuotation.quotationNumber) {
        const lastSequence = parseInt(lastQuotation.quotationNumber.slice(-4));
        if (!isNaN(lastSequence)) {
          sequence = lastSequence + 1;
        }
      }
      
      this.quotationNumber = `QT${year}${month}${String(sequence).padStart(4, '0')}`;
    } catch (error) {
      console.error('Error generating quotation number:', error);
      // Fallback to timestamp-based number if generation fails
      this.quotationNumber = `QT${Date.now()}`;
    }
  }
});

// Indexes
QuotationSchema.index({ quotationNumber: 1 });
QuotationSchema.index({ client: 1 });
QuotationSchema.index({ status: 1 });
QuotationSchema.index({ createdAt: -1 });
QuotationSchema.index({ validTill: 1 });

export default mongoose.models.Quotation || mongoose.model('Quotation', QuotationSchema);
